### ISSUE TITLE
Stop button is not working.

### ISSUE THREAD

**Issue by aryabartar** [1995parham/stopwatch#1]
When I click on Stop the time increases rather than just stopping time!

**Comment by aryabartar** [comment]
I noticed that this problem happens when I click on Start multiple times. 
Reset suffers from this problem too :(

**Comment by 1995parham** [comment]
Thanks for reporting issues. I updated it, can you check the newer version?

**Comment by aryabartar** [comment]
I checked it again but the bug still remains.
